### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by lkeegan** [dieterich-lab/pybio-utils#4]
To publish on pypi / bioconda a unique name is required:

- `pbio` is available on bioconda/conda-forge
  - work in progress recipe: https://github.com/bioconda/bioconda-recipes/pull/36324
- on pypi both [pbio](https://pypi.org/project/pbio) and [pybio](https://pypi.org/project/pybio/) are taken
  - `pybio-utils` is available
- also would it make sense to rename the repository to match the package name `pbio`?

**Comment by eboileau** [comment]
I think we should have the same name on bioconda and pypi, but if renaming the repository to `pbio`, this doesn't solve the pypi problem... or you mean the package? `pybio-utils` is rather clumsy to write... so I would actually change everything to _e.g._ `pbiotools`, which seem available on bioconda/forge and pypi.

**Comment by lkeegan** [comment]
I agree having the same name everywhere would be best - changing everything to `pbiotools` seems like a good solution to me!

**Comment by eboileau** [comment]
Ok, then I will merge #5 and restructure the package/repo, and rename to `pbiotools` (and make all necessary changes in the codes, incl. [rpbp](https://github.com/dieterich-lab/rp-bp))

**Comment by eboileau** [comment]
`pbiotools` (branch `dev-ssciwr`) sorted. I will make changes in rpbp.

**Comment by eboileau** [comment]
Done in [rpbp](https://github.com/dieterich-lab/rp-bp) (branch `dev-ssciwr`).
