### ISSUE TITLE
first bioconda/pypi release

### ISSUE THREAD

**Issue by lkeegan** [dieterich-lab/pybio-utils#8]
remaining steps for a first bioconda & pypi release:

- [X] create pypi [API token](https://pypi.org/help/#apitoken) and add it to github repo secrets with name `pypi_token` to allow CI to upload to pypi on tagged commits
- [X] merge `dev-ssciwr` branch to master
- [X] update version number, tag commit with version number
- [X] make github release from that tag
- [x] update https://github.com/bioconda/bioconda-recipes/pull/36324 to point to github release & request that it be merged

Afterwards, future releases should be very simple:

- update version, tag commit, make github release
  - CI will automatically deploy new version to pypi
  - bioconda has a bot that should automatically update the package whenever a new github release is made

**Comment by eboileau** [comment]
Thanks @lkeegan 
I bumped to a new major release. I'm not sure about the last point what should I do?

**Comment by lkeegan** [comment]
@eboileau great! For the last point I'll update the bioconda PR and ask for it to be merged

**Comment by eboileau** [comment]
@lkeegan What remains to do here?

**Comment by lkeegan** [comment]
@eboileau this is done, however now that rp-bp doesn't need the pystan<3 pin anymore it would probably be good to make a new release of pbiotools removing the explicit pystan<3 dependency (would also need to remove `pickle-stan --help` from the tests section):
- https://github.com/bioconda/bioconda-recipes/blob/57411afd6383d00a6c8dfa2201d8437fedbfc990/recipes/pbiotools/meta.yaml#L78

This would allow us to remove the python < 3.10 limitation that was required because of this pystan pin:
-  https://github.com/bioconda/bioconda-recipes/blob/57411afd6383d00a6c8dfa2201d8437fedbfc990/recipes/pbiotools/meta.yaml#L62


I'm on vacation now but happy to do thsi in Jan

**Comment by eboileau** [comment]
@lkeegan Thanks for your quick reply. I'm working on the docs now, and some other minor issues. When I'm done, I will then make this new release, so we can move forward. January is fine.

**Comment by eboileau** [comment]
I am mostly ready to release v3 (again bump to major version due to backwards incompatible changes), however
there seem to be a couple of tests failing with strange errors after merging your last PR...

[pip macOS 3.10](https://github.com/dieterich-lab/pbiotools/actions/runs/3884507509/jobs/6627162887)

[conda macOS 3.8](https://github.com/dieterich-lab/pbiotools/actions/runs/3883238931/jobs/6627392084)

Also note that the bioconda recipe (meta.yaml) needs to be updated to reflect latest changes in requirements and entry points (for instance pbiotools.ribo doesn't exists anymore...)

Could you please have a look?

**Comment by lkeegan** [comment]
Both test failures look like transient network issues - could you try re-running them?

Yes I'll update the bioconda recipe - I think it would make sense to do the github/pypi release first, then I can also update the version number & SHA in the recipe to point to the new version.

**Comment by eboileau** [comment]
Indeed, all tests completed successfully.

v3.0.0 just released.

**Comment by lkeegan** [comment]
Great! I'll update the bioconda recipe & make a PR there

**Comment by lkeegan** [comment]
PR is here: https://github.com/bioconda/bioconda-recipes/pull/38759
I also tried installing the build artefact from this PR into my local rp-bp (from [dev_dependencies](https://github.com/lkeegan/rp-bp/tree/dev_dependencies) branch) which only uses conda for the dependencies, no pypi, & the tests passed, so it looks good, now just need the PR to be merged.

**Comment by lkeegan** [comment]
closing this issue as pbiotools 3.0.0 is now available on bioconda
